### ISSUE TITLE
Very good

### ISSUE THREAD

**Issue by HUANGJIN169** [motion4sim/AASD15A-Servo-Controller-for-Motion-Simrigs#2]
A very good 6DOF drive board

**Comment by motion4sim** [comment]
Hi, you can contact me with email

 

here ***@***.***

 

or you connect to me via discord

 

motion4sim#4206

 

How may i help you?

 

Thank you

 

b.regards motion4sim


 

ps: i dont use meta services

 


Gesendet: Sonntag, 21. November 2021 um 15:55 Uhr
Von: "huangjin" ***@***.***>
An: "motion4sim/AASD15A-Servo-Controller-for-Motion-Simrigs" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [motion4sim/AASD15A-Servo-Controller-for-Motion-Simrigs] How to contact you? (Issue #2)


 

Hello, how can I contact you? Can I leave a message to get your contact information? Or Facebook.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
